/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations['health_api_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/layers': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Layers */
    get: operations['layers_api_layers_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/layers/{name}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Layer */
    get: operations['layer_api_layers__name__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/query': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Query
     * @description Run a query object (F-8.9); the result carries its query and provenance.
     */
    post: operations['query_api_query_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/query/validate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Validate
     * @description Check a query against schema and data core without running it (F-5.9).
     */
    post: operations['validate_api_query_validate_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/schema/query-object': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Query Object Schema
     * @description The versioned query-object JSON schema (F-10.3).
     */
    get: operations['query_object_schema_api_schema_query_object_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/tools': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Tools */
    get: operations['tools_api_tools_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * Aggregate
     * @description Summarise source features per feature of an area layer (F-4.7).
     *
     *     Every area feature appears in the result, with ``count`` 0 and other
     *     metrics null where no source feature relates to it.
     */
    Aggregate: {
      /**
       * By Layer
       * @description Lower-case layer or attribute name.
       */
      by_layer: string
      /**
       * Predicate
       * @description Relation 'source <predicate> area'.
       * @default within
       * @enum {string}
       */
      predicate: 'within' | 'intersects'
      /**
       * Area Fields
       * @description Attributes of ``by_layer`` kept in the result.
       */
      area_fields?: string[]
      /** Metrics */
      metrics: components['schemas']['Metric'][]
    }
    /** And */
    'And-Input': {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      op: 'and'
      /** Args */
      args: (
        | components['schemas']['Compare']
        | components['schemas']['Between']
        | components['schemas']['InList']
        | components['schemas']['TextMatch']
        | components['schemas']['IsNull']
        | components['schemas']['BBox']
        | components['schemas']['GeometryFilter']
        | components['schemas']['NearFeature']
        | components['schemas']['And-Input']
        | components['schemas']['Or-Input']
        | components['schemas']['Not-Input']
      )[]
    }
    /** And */
    'And-Output': {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      op: 'and'
      /** Args */
      args: (
        | components['schemas']['Compare']
        | components['schemas']['Between']
        | components['schemas']['InList']
        | components['schemas']['TextMatch']
        | components['schemas']['IsNull']
        | components['schemas']['BBox']
        | components['schemas']['GeometryFilter']
        | components['schemas']['NearFeature']
        | components['schemas']['And-Output']
        | components['schemas']['Or-Output']
        | components['schemas']['Not-Output']
      )[]
    }
    /** AttributeInfo */
    AttributeInfo: {
      /** Name */
      name: string
      /**
       * Data Type
       * @enum {string}
       */
      data_type: 'integer' | 'real' | 'text' | 'boolean'
      /** Label */
      label: string
      /** Description */
      description: string
      /** Unit */
      unit: string | null
      /** Value Domain */
      value_domain: {
        [key: string]: unknown
      } | null
    }
    /**
     * AttributeJoin
     * @description Left join of a layer by key (F-4.6).
     *
     *     Joined fields are addressable by their name, or by ``prefix + name`` when a
     *     prefix is given; clashes with source attributes are rejected.
     */
    AttributeJoin: {
      /**
       * Layer
       * @description Lower-case layer or attribute name.
       */
      layer: string
      /**
       * Left Key
       * @description Attribute of the source layer.
       */
      left_key: string
      /**
       * Right Key
       * @description Attribute of the joined layer.
       */
      right_key: string
      /** Fields */
      fields: string[]
      /** Prefix */
      prefix?: string | null
    }
    /**
     * BBox
     * @description Source geometry intersects a WGS84 bounding box, e.g. the map view (F-4.3).
     */
    BBox: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      op: 'bbox'
      /**
       * Bbox
       * @description [min_lon, min_lat, max_lon, max_lat] in WGS84.
       */
      bbox: [number, number, number, number]
    }
    /**
     * Between
     * @description Inclusive value range (F-4.2).
     */
    Between: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      op: 'between'
      /**
       * Attr
       * @description Lower-case layer or attribute name.
       */
      attr: string
      /** Min */
      min: number
      /** Max */
      max: number
    }
    /**
     * Buffer
     * @description Replace each source geometry by its buffer (F-4.5).
     */
    Buffer: {
      /**
       * Distance M
       * @description Distance in metres.
       */
      distance_m: number
    }
    /** Capabilities */
    Capabilities: {
      /** Supported */
      supported: components['schemas']['Op'][]
      /** Missing */
      missing: {
        [key: string]: string[]
      }
    }
    /** Categorized */
    Categorized: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: 'categorized'
      /**
       * Attr
       * @description Lower-case layer or attribute name.
       */
      attr: string
      /**
       * Colors
       * @description Optional fixed colour per category value.
       */
      colors?: {
        [key: string]: string
      }
    }
    /** Classified */
    Classified: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: 'classified'
      /**
       * Attr
       * @description Lower-case layer or attribute name.
       */
      attr: string
      /**
       * Method
       * @enum {string}
       */
      method: 'quantile' | 'equal_interval'
      /**
       * Classes
       * @default 5
       */
      classes: number
    }
    /**
     * Compare
     * @description Attribute comparison with a constant (F-4.2).
     */
    Compare: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      op: 'compare'
      /**
       * Attr
       * @description Lower-case layer or attribute name.
       */
      attr: string
      /**
       * Cmp
       * @enum {string}
       */
      cmp: 'eq' | 'ne' | 'lt' | 'le' | 'gt' | 'ge'
      /** Value */
      value: string | number | boolean
    }
    /** ErrorBody */
    ErrorBody: {
      /** Code */
      code: string
      /** Message */
      message: string
      /**
       * Details
       * @default {}
       */
      details: {
        [key: string]: unknown
      }
    }
    /** Feature */
    Feature: {
      /**
       * Type
       * @default Feature
       * @constant
       */
      type: 'Feature'
      /** Id */
      id: number
      /** Properties */
      properties: {
        [key: string]: unknown
      }
      /** Geometry */
      geometry: {
        [key: string]: unknown
      } | null
    }
    /**
     * GeoJSONGeometry
     * @description GeoJSON geometry in WGS84. Coordinates are checked when compiled.
     */
    GeoJSONGeometry: {
      /**
       * Type
       * @enum {string}
       */
      type: 'Point' | 'MultiPoint' | 'LineString' | 'MultiLineString' | 'Polygon' | 'MultiPolygon'
      /** Coordinates */
      coordinates: unknown[]
    }
    /**
     * GeometryFilter
     * @description Source geometry relates to a drawn geometry (F-4.3).
     */
    GeometryFilter: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      op: 'geometry'
      geometry: components['schemas']['GeoJSONGeometry']
      /**
       * Predicate
       * @default intersects
       * @enum {string}
       */
      predicate: 'intersects' | 'within' | 'contains'
    }
    /** GraduatedSize */
    GraduatedSize: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: 'graduated_size'
      /**
       * Attr
       * @description Lower-case layer or attribute name.
       */
      attr: string
      /**
       * Min Size
       * @default 4
       */
      min_size: number
      /**
       * Max Size
       * @default 24
       */
      max_size: number
    }
    /** Health */
    Health: {
      /**
       * Status
       * @enum {string}
       */
      status: 'ok' | 'degraded'
      /** Version */
      version: string
      /** Backend */
      backend: string
      /** Internal Crs */
      internal_crs: number
      /** Schema Version */
      schema_version: string
      /** Sample Dataset Version */
      sample_dataset_version: string
      capabilities: components['schemas']['Capabilities']
    }
    /**
     * InList
     * @description Value in list (F-4.2).
     */
    InList: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      op: 'in'
      /**
       * Attr
       * @description Lower-case layer or attribute name.
       */
      attr: string
      /** Values */
      values: (string | number | boolean)[]
    }
    /**
     * IsNull
     * @description Attribute has no value. Combine with ``not`` for 'has a value'.
     */
    IsNull: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      op: 'is_null'
      /**
       * Attr
       * @description Lower-case layer or attribute name.
       */
      attr: string
    }
    /** LayerInfo */
    LayerInfo: {
      /** Name */
      name: string
      /** Title */
      title: string
      /** Description */
      description: string
      /**
       * Kind
       * @enum {string}
       */
      kind: 'vector' | 'table'
      /** Geometry Type */
      geometry_type: string | null
      /** Feature Count */
      feature_count: number
      /** Bbox Wgs84 */
      bbox_wgs84: number[] | null
      /** Dataset Version */
      dataset_version: string | null
      /** Attributes */
      attributes: components['schemas']['AttributeInfo'][]
    }
    /** Metric */
    Metric: {
      /**
       * Fn
       * @enum {string}
       */
      fn: 'count' | 'sum' | 'avg' | 'min' | 'max'
      /**
       * Attr
       * @description Source attribute; not used by 'count'.
       */
      attr?: string | null
      /**
       * As
       * @description Name of the result attribute.
       */
      as: string
    }
    /**
     * NearFeature
     * @description Source geometry lies within a distance of one reference feature (F-4.3).
     */
    NearFeature: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      op: 'near_feature'
      /**
       * Layer
       * @description Lower-case layer or attribute name.
       */
      layer: string
      /** Fid */
      fid: number
      /**
       * Distance M
       * @description Distance in metres.
       * @default 0
       */
      distance_m: number
    }
    /** Not */
    'Not-Input': {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      op: 'not'
      /** Arg */
      arg:
        | components['schemas']['Compare']
        | components['schemas']['Between']
        | components['schemas']['InList']
        | components['schemas']['TextMatch']
        | components['schemas']['IsNull']
        | components['schemas']['BBox']
        | components['schemas']['GeometryFilter']
        | components['schemas']['NearFeature']
        | components['schemas']['And-Input']
        | components['schemas']['Or-Input']
        | components['schemas']['Not-Input']
    }
    /** Not */
    'Not-Output': {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      op: 'not'
      /** Arg */
      arg:
        | components['schemas']['Compare']
        | components['schemas']['Between']
        | components['schemas']['InList']
        | components['schemas']['TextMatch']
        | components['schemas']['IsNull']
        | components['schemas']['BBox']
        | components['schemas']['GeometryFilter']
        | components['schemas']['NearFeature']
        | components['schemas']['And-Output']
        | components['schemas']['Or-Output']
        | components['schemas']['Not-Output']
    }
    /**
     * Op
     * @description Registered operations; each needs certain logical dialect functions (F-2.14).
     * @enum {string}
     */
    Op:
      | 'attribute_filter'
      | 'bbox_filter'
      | 'geometry_filter'
      | 'near_feature'
      | 'attribute_join'
      | 'buffer'
      | 'spatial_relation'
      | 'aggregate'
    /** Or */
    'Or-Input': {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      op: 'or'
      /** Args */
      args: (
        | components['schemas']['Compare']
        | components['schemas']['Between']
        | components['schemas']['InList']
        | components['schemas']['TextMatch']
        | components['schemas']['IsNull']
        | components['schemas']['BBox']
        | components['schemas']['GeometryFilter']
        | components['schemas']['NearFeature']
        | components['schemas']['And-Input']
        | components['schemas']['Or-Input']
        | components['schemas']['Not-Input']
      )[]
    }
    /** Or */
    'Or-Output': {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      op: 'or'
      /** Args */
      args: (
        | components['schemas']['Compare']
        | components['schemas']['Between']
        | components['schemas']['InList']
        | components['schemas']['TextMatch']
        | components['schemas']['IsNull']
        | components['schemas']['BBox']
        | components['schemas']['GeometryFilter']
        | components['schemas']['NearFeature']
        | components['schemas']['And-Output']
        | components['schemas']['Or-Output']
        | components['schemas']['Not-Output']
      )[]
    }
    /** OrderBy */
    OrderBy: {
      /**
       * Attr
       * @description Lower-case layer or attribute name.
       */
      attr: string
      /**
       * Dir
       * @default asc
       * @enum {string}
       */
      dir: 'asc' | 'desc'
    }
    /**
     * GeoTandem query object
     * @description Declarative, backend-neutral description of one analysis.
     */
    'QueryObject-Input': {
      /**
       * Schema Version
       * @default 0
       * @constant
       */
      schema_version: '0'
      /**
       * Source
       * @description Lower-case layer or attribute name.
       */
      source: string
      attribute_join?: components['schemas']['AttributeJoin'] | null
      /** Where */
      where?:
        | (
            | components['schemas']['Compare']
            | components['schemas']['Between']
            | components['schemas']['InList']
            | components['schemas']['TextMatch']
            | components['schemas']['IsNull']
            | components['schemas']['BBox']
            | components['schemas']['GeometryFilter']
            | components['schemas']['NearFeature']
            | components['schemas']['And-Input']
            | components['schemas']['Or-Input']
            | components['schemas']['Not-Input']
          )
        | null
      buffer?: components['schemas']['Buffer'] | null
      spatial_relation?: components['schemas']['SpatialRelation-Input'] | null
      aggregate?: components['schemas']['Aggregate'] | null
      /**
       * Select
       * @description Result attributes; all when omitted.
       */
      select?: string[] | null
      /** Order By */
      order_by?: components['schemas']['OrderBy'][]
      /** Limit */
      limit?: number | null
      /** Symbology */
      symbology?:
        | (
            | components['schemas']['SingleSymbol']
            | components['schemas']['Categorized']
            | components['schemas']['Classified']
            | components['schemas']['GraduatedSize']
          )
        | null
      /**
       * Output
       * @default map
       * @enum {string}
       */
      output: 'map' | 'table'
    }
    /**
     * GeoTandem query object
     * @description Declarative, backend-neutral description of one analysis.
     */
    'QueryObject-Output': {
      /**
       * Schema Version
       * @default 0
       * @constant
       */
      schema_version: '0'
      /**
       * Source
       * @description Lower-case layer or attribute name.
       */
      source: string
      attribute_join?: components['schemas']['AttributeJoin'] | null
      /** Where */
      where?:
        | (
            | components['schemas']['Compare']
            | components['schemas']['Between']
            | components['schemas']['InList']
            | components['schemas']['TextMatch']
            | components['schemas']['IsNull']
            | components['schemas']['BBox']
            | components['schemas']['GeometryFilter']
            | components['schemas']['NearFeature']
            | components['schemas']['And-Output']
            | components['schemas']['Or-Output']
            | components['schemas']['Not-Output']
          )
        | null
      buffer?: components['schemas']['Buffer'] | null
      spatial_relation?: components['schemas']['SpatialRelation-Output'] | null
      aggregate?: components['schemas']['Aggregate'] | null
      /**
       * Select
       * @description Result attributes; all when omitted.
       */
      select?: string[] | null
      /** Order By */
      order_by?: components['schemas']['OrderBy'][]
      /** Limit */
      limit?: number | null
      /** Symbology */
      symbology?:
        | (
            | components['schemas']['SingleSymbol']
            | components['schemas']['Categorized']
            | components['schemas']['Classified']
            | components['schemas']['GraduatedSize']
          )
        | null
      /**
       * Output
       * @default map
       * @enum {string}
       */
      output: 'map' | 'table'
    }
    /**
     * QueryResult
     * @description A GeoJSON FeatureCollection plus the query and its provenance.
     */
    QueryResult: {
      /**
       * Type
       * @default FeatureCollection
       * @constant
       */
      type: 'FeatureCollection'
      /** Features */
      features: components['schemas']['Feature'][]
      query: components['schemas']['QueryObject-Output']
      meta: components['schemas']['ResultMeta']
    }
    /** ResultMeta */
    ResultMeta: {
      /** Schema Version */
      schema_version: string
      /**
       * Query Hash
       * @description sha256 of the canonical query object.
       */
      query_hash: string
      /**
       * Data Versions
       * @description Dataset version of every layer the query touched.
       */
      data_versions: {
        [key: string]: string | null
      }
      /** Backend */
      backend: string
      /** Feature Count */
      feature_count: number
      /** Elapsed Ms */
      elapsed_ms: number
    }
    /** SingleSymbol */
    SingleSymbol: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: 'single'
      /**
       * Color
       * @default #3366cc
       */
      color: string
    }
    /**
     * SpatialRelation
     * @description Keep source features related to at least one feature of ``layer`` (F-4.4).
     *
     *     The predicate reads ``source <predicate> layer``: ``within`` keeps source
     *     features lying inside a feature of ``layer``.
     */
    'SpatialRelation-Input': {
      /**
       * Layer
       * @description Lower-case layer or attribute name.
       */
      layer: string
      /**
       * Predicate
       * @enum {string}
       */
      predicate: 'intersects' | 'within' | 'contains' | 'dwithin'
      /** Distance M */
      distance_m?: number | null
      /**
       * Where
       * @description Filter on the attributes of ``layer``.
       */
      where?:
        | (
            | components['schemas']['Compare']
            | components['schemas']['Between']
            | components['schemas']['InList']
            | components['schemas']['TextMatch']
            | components['schemas']['IsNull']
            | components['schemas']['BBox']
            | components['schemas']['GeometryFilter']
            | components['schemas']['NearFeature']
            | components['schemas']['And-Input']
            | components['schemas']['Or-Input']
            | components['schemas']['Not-Input']
          )
        | null
    }
    /**
     * SpatialRelation
     * @description Keep source features related to at least one feature of ``layer`` (F-4.4).
     *
     *     The predicate reads ``source <predicate> layer``: ``within`` keeps source
     *     features lying inside a feature of ``layer``.
     */
    'SpatialRelation-Output': {
      /**
       * Layer
       * @description Lower-case layer or attribute name.
       */
      layer: string
      /**
       * Predicate
       * @enum {string}
       */
      predicate: 'intersects' | 'within' | 'contains' | 'dwithin'
      /** Distance M */
      distance_m?: number | null
      /**
       * Where
       * @description Filter on the attributes of ``layer``.
       */
      where?:
        | (
            | components['schemas']['Compare']
            | components['schemas']['Between']
            | components['schemas']['InList']
            | components['schemas']['TextMatch']
            | components['schemas']['IsNull']
            | components['schemas']['BBox']
            | components['schemas']['GeometryFilter']
            | components['schemas']['NearFeature']
            | components['schemas']['And-Output']
            | components['schemas']['Or-Output']
            | components['schemas']['Not-Output']
          )
        | null
    }
    /**
     * TextMatch
     * @description Text search in a string attribute (F-4.2).
     */
    TextMatch: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      op: 'text_match'
      /**
       * Attr
       * @description Lower-case layer or attribute name.
       */
      attr: string
      /** Text */
      text: string
      /**
       * Mode
       * @default contains
       * @enum {string}
       */
      mode: 'contains' | 'starts_with' | 'ends_with' | 'equals'
      /**
       * Case Sensitive
       * @default false
       */
      case_sensitive: boolean
    }
    /** ToolDescription */
    ToolDescription: {
      /** Name */
      name: string
      /** Description */
      description: string
      /**
       * Effect
       * @enum {string}
       */
      effect: 'read' | 'state'
      /** Input Schema */
      input_schema: {
        [key: string]: unknown
      }
      /** Output Schema */
      output_schema: {
        [key: string]: unknown
      }
    }
    /** Validation */
    Validation: {
      /**
       * Valid
       * @default true
       * @constant
       */
      valid: true
      /** Layers */
      layers: string[]
      /** Operations */
      operations: components['schemas']['Op'][]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Health']
        }
      }
    }
  }
  layers_api_layers_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LayerInfo'][]
        }
      }
    }
  }
  layer_api_layers__name__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        name: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LayerInfo']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Content Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Gateway Timeout */
      504: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  query_api_query_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['QueryObject-Input']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['QueryResult']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Content Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Gateway Timeout */
      504: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  validate_api_query_validate_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['QueryObject-Input']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Validation']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Content Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Gateway Timeout */
      504: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  query_object_schema_api_schema_query_object_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
    }
  }
  tools_api_tools_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ToolDescription'][]
        }
      }
    }
  }
}
